name: shtt_bentre
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.7.5+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2  
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  postgres: ^2.5.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_widget_from_html: ^0.15.2
  fl_chart: ^0.69.2
  flutter_html: ^3.0.0-beta.2
  http: ^0.13.6
  mailer: ^6.3.0
  package_info_plus: ^8.1.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  dialog_flowtter: ^0.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - lib/assets/
    - lib/assets/map/
    - assets/dialog_flow_auth.json
